PAYROLL	STRUC
NAM	DB	10 DUP('A')
POST	DB	'ENGINEER    '
WAGES	DW	?
PAYROLL	ENDS

DATA	SEGMENT
NO1	PAYROLL <>
NO2	PAYROLL	<,'WORKER',900>
NO3_32	PAYROLL 30 DUP(<>)
DATA	ENDS

CODE	SEGMENT
	ASSUME  CS:CODE, DS:DATA
MAIN	PROC	FAR
	MOV	AX, DATA
	MOV	DS, AX
	MOV	NO1.WAGES, 1200
	MOV	AX, NO1.WAGES
	LEA	BX, NO3_32
	MOV	[BX].WAGES, 1500
	XOR	SI, SI
	MOV	[BX].NAM[SI], 'C'
       	MOV     AX, 4C00H
       	INT     21H
MAIN	ENDP
CODE	ENDS
	END	MAIN
