INCLUDE	 MACRO.LIB

PURGE	SETMODE, INCHAR, OUTCHAR, CURSOR, PUTC, PUTS, WINDOW

STACKSG	    SEGMENT   STACK 'S'
	DW    64    DUP('?')
STACKSG	    ENDS

DATA	SEGMENT
	A      DD	  7006652		    ;被除数
	B      DW	   1234		    ;除数
	C      DW	   ?		    ;商
	PROMPT	  DB   'The result is: $'
	ASCII	DB     5 DUP(?),'$'	    ;转换结果
DATA	ENDS

CODE	SEGMENT
	ASSUME	 CS:CODE , DS:DATA , SS:STACKSG
MAIN	PROC	FAR
	MOV	AX,DATA
	MOV	DS,AX

	MOV	DX,WORD  PTR  A+2
	MOV	AX,WORD  PTR  A
	DIV	B

	BIN_DEC	ASCII,AX
	CLRSCRN
	DISP	PROMPT
	DISP	ASCII
	RETURN
MAIN	ENDP
CODE	ENDS
	END	MAIN
